name: Build Gradle project

on:
  push:
permissions:
  checks: write
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
         report_paths: '**/build/test-results/test/TEST-*.xml'